version: '3.1'
services:
  background_worker:
    build:
      context: "./behind_redis_background_worker/"
      dockerfile: "Dockerfile.dev"
    ports:
      - "4000:4000"
    volumes:
      - "./behind_redis_background_worker:/app"
  main_backend:
    build:
      context: "./express_backend"
      dockerfile: "Dockerfile.dev"
    ports:
      - "3000:3000"
    volumes:
      - "./express_backend:/app"
  db:
    # successfully connected directly to db with
    # docker exec --user postgres -it docker_compose_postgres_test_db_1 psql
    # -h localhost -U postgres
    # but this was just a sanity check
    # update: worked perfectly fine connecting from node/express
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
  rediscache:
    image: redis:alpine
    ports:
      - "6379:6379"
  # webapp:
    # build: .
    # depends_on: db
